### ISSUE TITLE
AttributeError: 'list' object attribute 'append' is read-only in bin/create_final_json.py

### ISSUE THREAD

**Issue by WhalleyT** [Pathogen-Genomics-Cymru/tb-pipeline#27]
The create_final_json.py script fails when trying to append to a list used to create the warnings field in the final JSON in process clockwork:alignToRef:

`Traceback (most recent call last):
    File "/scratch/c.c1656075/sp3_testing_2/tb-pipeline/bin/create_final_json.py", line 128, in <module>
      out = read_and_parse_input_files(stats_file, report_file)
    File "/scratch/c.c1656075/sp3_testing_2/tb-pipeline/bin/create_final_json.py", line 96, in read_and_parse_input_files
      warnings.append = "there was %d error but no warnings" %num_errors
  AttributeError: 'list' object attribute 'append' is read-only`

It appears this is because the script is trying to assign to a member called `append` rather than append to the `warnings` list.

**Comment by annacprice** [comment]
fixed on cardiff-testing
